apiVersion: v1
kind: Namespace
metadata:
  name: service-dhpup-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-dhpup-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-dhpup-prod
