apiVersion: v1
kind: Namespace
metadata:
  name: service-palamvmw-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-palamvmw-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: service-palamvmw-prod
