apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dakotalillie
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-dakotalillie-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:dakotalillie:admin, *, *, dakotalillie/*, allow
    groups:
    - dakota.lillie@icloud.com

