# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: dhpup
# spec:
#   sourceRepos:
#     - '*'
#   destinations:
#     - namespace: 'service-dhpup-*'
#       server: http://cluster-argocon:8001
#   roles:
#   - name: admin
#     policies:
#     - p, proj:dhpup:admin, *, *, dhpup/*, allow
#     groups:
#     - danielvanhoang@gmail.com # please copy it from https://argocon.cd.akuity.cloud/user-info
