apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jtmilan
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-jtmilan-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:jtmilan:admin, *, *, jtmilan/*, allow
    groups:
    - <EMAIL> # please copy it from https://argocon.cd.akuity.cloud/user-info