apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lcenta
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-lcenta-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:lcenta:admin, *, *, lcenta/*, allow
    groups:
    - lanncenta@gmail.com # please copy it from https://argocon.cd.akuity.cloud/user-info
