apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: morey-tech
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-morey-tech-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:morey-tech:admin, *, *, morey-tech/*, allow
    groups:
    - gcdcai6k@duck.com # please copy it from https://argocon.cd.akuity.cloud/user-info
