
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nikita
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-<USERNAME>-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:nikita:admin, *, *, nikita/*, allow
    groups:
    - nikita@akuity.io # please copy it from https://argocon.cd.akuity.cloud/user-info
