apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ofominykh
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-ofominykh-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:ofominykh:admin, *, *, ofominykh/*, allow
    groups:
    - ofominykh@shotspotter.com # please copy it from https://argocon.cd.akuity.cloud/user-info
