apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pmithil7
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-pmithil7-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:pmithil7:admin, *, *, pmithil7/*, allow
    groups:
    - mitpatel@equinix.com
