apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: evgeny-goldin
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'service-evgeny-goldin-*'
      server: http://cluster-argocon:8001
  roles:
  - name: admin
    policies:
    - p, proj:<USERNAME>:admin, *, *, <USERNAME>/*, allow
    groups:
    - evgenyg@gmail.com
