# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: <USERNAME>
# spec:
#   sourceRepos:
#     - '*'
#   destinations:
#     - namespace: 'service-<USERNAME>-*'
#       server: http://cluster-argocon:8001
#   roles:
#   - name: admin
#     policies:
#     - p, proj:<USERNAME>:admin, *, *, <USERNAME>/*, allow
#     groups:
#     - <EMAIL> # please copy it from https://argocon.cd.akuity.cloud/user-info
